### ISSUE TITLE
build之后，程序无法正常访问

### ISSUE THREAD

**Issue by xxyjskx1987** [microzz/vue-chat#4]
POST http://localhost/socket.io/?EIO=3&transport=polling&t=LmQuiI4 404 (Not Found)

**Comment by microzz** [comment]
@xxyjskx1987 需要web服务器

**Comment by xxyjskx1987** [comment]
@microzz 有web服务器的

**Comment by microzz** [comment]
@xxyjskx1987 我试了一下是没问题的

**Comment by xxyjskx1987** [comment]
@microzz 需要用run dev启动express么

**Comment by microzz** [comment]
@xxyjskx1987 请先正确安装所有依赖
