### ISSUE TITLE
本地npm start  之后显示localhost拒绝访问

### ISSUE THREAD

**Issue by xingyibiao** [microzz/vue-chat#5]
node 版本6.9.5
npm 版本3.10.10

**Comment by microzz** [comment]
@xingyibiao 请确保所有依赖都正确安装，推荐翻墙或者cnpm，然后再次尝试npm run dev，打开http://localhost:8080

**Comment by xingyibiao** [comment]
依赖已经正确安装了，控制台也打印 listen at。我重新检查了一下npm install,  只有一个warning  是fsevents的，我试了下别的应用可以正常启动。 不知道哪里出问题了

**Comment by microzz** [comment]
@xingyibiao 我测试是正常的

**Comment by xingyibiao** [comment]
我再找一下哪里出现问题了，辛苦了大神

**Comment by xingyibiao** [comment]
找到问题所在了，dev.server.js 里面你的server.listen写死了，只能在8080端口启动。将其改为server.listen(port)就好了。
